
const CHARACTERISTIC_UUID = {
    "DEVICE_NAME": 0x2A00,
    "APPEARANCE": 0x2A01,
    "PERIPHERAL_PRIVACY_FLAG": 0x2A02,
    "RECONNECTION_ADDRESS": 0x2A03,
    "PERIPHERAL_PREFERRED_CONNECTION_PARAMETERS": 0x2A04,
    "SERVICE_CHANGED": 0x2A05,
    "ALERT_LEVEL": 0x2A06,
    "TX_POWER_LEVEL": 0x2A07,
    "DATE_TIME": 0x2A08,
    "DAY_OF_WEEK": 0x2A09,
    "DAY_DATE_TIME": 0x2A0A,
    "EXACT_TIME_256": 0x2A0C,
    "DST_OFFSET": 0x2A0D,
    "TIME_ZONE": 0x2A0E,
    "LOCAL_TIME_INFORMATION": 0x2A0F,
    "TIME_WITH_DST": 0x2A11,
    "TIME_ACCURACY": 0x2A12,
    "TIME_SOURCE": 0x2A13,
    "REFERENCE_TIME_INFORMATION": 0x2A14,
    "TIME_UPDATE_CONTROL_POINT": 0x2A16,
    "TIME_UPDATE_STATE": 0x2A17,
    "GLUCOSE_MEASUREMENT": 0x2A18,
    "BATTERY_LEVEL": 0x2A19,
    "BATTERY_LEVEL_STATE": 0x2A1B,
    "TEMPERATURE_MEASUREMENT": 0x2A1C,
    "TEMPERATURE_TYPE": 0x2A1D,
    "INTERMEDIATE_TEMPERATURE": 0x2A1E,
    "MEASUREMENT_INTERVAL": 0x2A21,
    "BOOT_KEYBOARD_INPUT_REPORT": 0x2A22,
    "SYSTEM_ID": 0x2A23,
    "MODEL_NUMBER_STRING": 0x2A24,
    "SERIAL_NUMBER_STRING": 0x2A25,
    "FIRMWARE_REVISION_STRING": 0x2A26,
    "HARDWARE_REVISION_STRING": 0x2A27,
    "SOFTWARE_REVISION_STRING": 0x2A28,
    "MANUFACTURER_NAME_STRING": 0x2A29,
    "IEEE_11073_20601_REGULATORY_CERTIFICATION_DATA_LIST": 0x2A2A,
    "CURRENT_TIME": 0x2A2B,
    "SCAN_REFRESH": 0x2A31,
    "BOOT_KEYBOARD_OUTPUT_REPORT": 0x2A32,
    "BOOT_MOUSE_INPUT_REPORT": 0x2A33,
    "GLUCOSE_MEASUREMENT_CONTEXT": 0x2A34,
    "BLOOD_PRESSURE_MEASUREMENT": 0x2A35,
    "INTERMEDIATE_CUFF_PRESSURE": 0x2A36,
    "HEART_RATE_MEASUREMENT": 0x2A37,
    "BODY_SENSOR_LOCATION": 0x2A38,
    "HEART_RATE_CONTROL_POINT": 0x2A39,
    "ALERT_STATUS": 0x2A3F,
    "RINGER_CONTROL_POINT": 0x2A40,
    "RINGER_SETTING": 0x2A41,
    "ALERT_CATEGORY_ID_BIT_MASK": 0x2A42,
    "ALERT_CATEGORY_ID": 0x2A43,
    "ALERT_NOTIFICATION_CONTROL_POINT": 0x2A44,
    "UNREAD_ALERT_STATUS": 0x2A45,
    "NEW_ALERT": 0x2A46,
    "SUPPORTED_NEW_ALERT_CATEGORY": 0x2A47,
    "SUPPORTED_UNREAD_ALERT_CATEGORY": 0x2A48,
    "BLOOD_PRESSURE_FEATURE": 0x2A49,
    "HID_INFORMATION": 0x2A4A,
    "REPORT_MAP": 0x2A4B,
    "HID_CONTROL_POINT": 0x2A4C,
    "REPORT": 0x2A4D,
    "PROTOCOL_MODE": 0x2A4E,
    "SCAN_INTERVAL_WINDOW": 0x2A4F,
    "PNP_ID": 0x2A50,
    "GLUCOSE_FEATURE": 0x2A51,
    "RECORD_ACCESS_CONTROL_POINT": 0x2A52,
    "RSC_MEASUREMENT": 0x2A53,
    "RSC_FEATURE": 0x2A54,
    "SC_CONTROL_POINT": 0x2A55,
    "AGGREGATE": 0x2A5A,
    "CSC_MEASUREMENT": 0x2A5B,
    "CSC_FEATURE": 0x2A5C,
    "SENSOR_LOCATION": 0x2A5D,
    "PLX_SPOT_CHECK_MEASUREMENT": 0x2A5E,
    "PLX_CONTINUOUS_MEASUREMENT": 0x2A5F,
    "PLX_FEATURES": 0x2A60,
    "CYCLING_POWER_MEASUREMENT": 0x2A63,
    "CYCLING_POWER_VECTOR": 0x2A64,
    "CYCLING_POWER_FEATURE": 0x2A65,
    "CYCLING_POWER_CONTROL_POINT": 0x2A66,
    "LOCATION_AND_SPEED": 0x2A67,
    "NAVIGATION": 0x2A68,
    "POSITION_QUALITY": 0x2A69,
    "LN_FEATURE": 0x2A6A,
    "LN_CONTROL_POINT": 0x2A6B,
    "ELEVATION": 0x2A6C,
    "PRESSURE": 0x2A6D,
    "TEMPERATURE": 0x2A6E,
    "HUMIDITY": 0x2A6F,
    "TRUE_WIND_SPEED": 0x2A70,
    "TRUE_WIND_DIRECTION": 0x2A71,
    "APPARENT_WIND_SPEED": 0x2A72,
    "APPARENT_WIND_DIRECTION": 0x2A73,
    "GUST_FACTOR": 0x2A74,
    "POLLEN_CONCENTRATION": 0x2A75,
    "UV_INDEX": 0x2A76,
    "IRRADIANCE": 0x2A77,
    "RAINFALL": 0x2A78,
    "WIND_CHILL": 0x2A79,
    "HEAT_INDEX": 0x2A7A,
    "DEW_POINT": 0x2A7B,
    "DESCRIPTOR_VALUE_CHANGED": 0x2A7D,
    "AEROBIC_HEART_RATE_LOWER_LIMIT": 0x2A7E,
    "AEROBIC_THRESHOLD": 0x2A7F,
    "AGE": 0x2A80,
    "ANAEROBIC_HEART_RATE_LOWER_LIMIT": 0x2A81,
    "ANAEROBIC_HEART_RATE_UPPER_LIMIT": 0x2A82,
    "ANAEROBIC_THRESHOLD": 0x2A83,
    "AEROBIC_HEART_RATE_UPPER_LIMIT": 0x2A84,
    "DATE_OF_BIRTH": 0x2A85,
    "DATE_OF_THRESHOLD_ASSESSMENT": 0x2A86,
    "EMAIL_ADDRESS": 0x2A87,
    "FAT_BURN_HEART_RATE_LOWER_LIMIT": 0x2A88,
    "FAT_BURN_HEART_RATE_UPPER_LIMIT": 0x2A89,
    "FIRST_NAME": 0x2A8A,
    "FIVE_ZONE_HEART_RATE_LIMITS": 0x2A8B,
    "GENDER": 0x2A8C,
    "HEART_RATE_MAX": 0x2A8D,
    "HEIGHT": 0x2A8E,
    "HIP_CIRCUMFERENCE": 0x2A8F,
    "LAST_NAME": 0x2A90,
    "MAXIMUM_RECOMMENDED_HEART_RATE": 0x2A91,
    "RESTING_HEART_RATE": 0x2A92,
    "SPORT_TYPE_FOR_AEROBIC_AND_ANAEROBIC_THRESHOLDS": 0x2A93,
    "THREE_ZONE_HEART_RATE_LIMITS": 0x2A94,
    "TWO_ZONE_HEART_RATE_LIMITS": 0x2A95,
    "VO2_MAX": 0x2A96,
    "WAIST_CIRCUMFERENCE": 0x2A97,
    "WEIGHT": 0x2A98,
    "DATABASE_CHANGE_INCREMENT": 0x2A99,
    "USER_INDEX": 0x2A9A,
    "BODY_COMPOSITION_FEATURE": 0x2A9B,
    "BODY_COMPOSITION_MEASUREMENT": 0x2A9C,
    "WEIGHT_MEASUREMENT": 0x2A9D,
    "WEIGHT_SCALE_FEATURE": 0x2A9E,
    "USER_CONTROL_POINT": 0x2A9F,
    "MAGNETIC_FLUX_DENSITY_2D": 0x2AA0,
    "MAGNETIC_FLUX_DENSITY_3D": 0x2AA1,
    "LANGUAGE": 0x2AA2,
    "BAROMETRIC_PRESSURE_TREND": 0x2AA3,
    "BOND_MANAGEMENT_CONTROL_POINT": 0x2AA4,
    "BOND_MANAGEMENT_FEATURE": 0x2AA5,
    "CENTRAL_ADDRESS_RESOLUTION": 0x2AA6,
    "CGM_MEASUREMENT": 0x2AA7,
    "CGM_FEATURE": 0x2AA8,
    "CGM_STATUS": 0x2AA9,
    "CGM_SESSION_START_TIME": 0x2AAA,
    "CGM_SESSION_RUN_TIME": 0x2AAB,
    "CGM_SPECIFIC_OPS_CONTROL_POINT": 0x2AAC,
    "INDOOR_POSITIONING_CONFIGURATION": 0x2AAD,
    "LATITUDE": 0x2AAE,
    "LONGITUDE": 0x2AAF,
    "LOCAL_NORTH_COORDINATE": 0x2AB0,
    "LOCAL_EAST_COORDINATE": 0x2AB1,
    "FLOOR_NUMBER": 0x2AB2,
    "ALTITUDE": 0x2AB3,
    "UNCERTAINTY": 0x2AB4,
    "LOCATION_NAME": 0x2AB5,
    "URI": 0x2AB6,
    "HTTP_HEADERS": 0x2AB7,
    "HTTP_STATUS_CODE": 0x2AB8,
    "HTTP_ENTITY_BODY": 0x2AB9,
    "HTTP_CONTROL_POINT": 0x2ABA,
    "HTTPS_SECURITY": 0x2ABB,
    "TDS_CONTROL_POINT": 0x2ABC,
    "OTS_FEATURE": 0x2ABD,
    "OBJECT_NAME": 0x2ABE,
    "OBJECT_TYPE": 0x2ABF,
    "OBJECT_SIZE": 0x2AC0,
    "OBJECT_FIRST_CREATED": 0x2AC1,
    "OBJECT_LAST_MODIFIED": 0x2AC2,
    "OBJECT_ID": 0x2AC3,
    "OBJECT_PROPERTIES": 0x2AC4,
    "OBJECT_ACTIONCONTROL_POINT": 0x2AC5,
    "OBJECT_LIST_CONTROL_POINT": 0x2AC6,
    "OBJECT_LIST_FILTER": 0x2AC7,
    "OBJECT_CHANGED": 0x2AC8,
    "RESOLVABLE_PRIVATE_ADDRESS_ONLY": 0x2AC9,
    "UNSPECIFIED": 0x2ACA,
    "DIRECTORY_LISTING": 0x2ACB,
    "FITNESS_MACHINE_FEATURE": 0x2ACC,
    "TREADMILL_DATA": 0x2ACD,
    "CROSS_TRAINER_DATA": 0x2ACE,
    "STEP_CLIMBER_DATA": 0x2ACF,
    "STAIR_CLIMBER_DATA": 0x2AD0,
    "ROWER_DATA": 0x2AD1,
    "INDOOR_BIKE_DATA": 0x2AD2,
    "TRAINING_STATUS": 0x2AD3,
    "SUPPORTED_SPEED_RANGE": 0x2AD4,
    "SUPPORTED_INCLINATION_RANGE": 0x2AD5,
    "SUPPORTED_RESISTANCE_LEVEL_RANGE": 0x2AD6,
    "SUPPORTED_HEART_RATE_RANGE": 0x2AD7,
    "SUPPORTED_POWER_RANGE": 0x2AD8,
    "FITNESS_MACHINE_CONTROL_POINT": 0x2AD9,
    "FITNESS_MACHINE_STATUS": 0x2ADA,
    "MESH_PROVISIONING_DATA_IN": 0x2ADB,
    "MESH_PROVISIONING_DATA_OUT": 0X2ADC,
    "MESH_PROXY_DATA_IN": 0X2ADD,
    "MESH_PROXY_DATA_OUT": 0X2ADE,
    "AVERAGE_CURRENT": 0X2AE0,
    "AVERAGE_VOLTAGE": 0X2AE1,
    "BOOLEAN": 0X2AE2,
    "CHROMATIC_DISTANCE_FROM_PLANCKIAN": 0X2AE3,
    "CHROMATICITY_COORDINATES": 0X2AE4,
    "CHROMATICITY_IN_CCT_AND_DUV_VALUES": 0X2AE5,
    "CHROMATICITY_TOLERANCE": 0X2AE6,
    "CIE_13_3_1995_COLOR_RENDERING_INDEX": 0X2AE7,
    "COEFFICIENT": 0X2AE8,
    "CORRELATED_COLOR_TEMPERATURE": 0X2AE9,
    "COUNT_16": 0X2AEA,
    "COUNT_24": 0X2AEB,
    "COUNTRY_CODE": 0X2AEC,
    "DATE_UTC": 0X2AED,
    "ELECTRIC_CURRENT": 0X2AEE,
    "ELECTRIC_CURRENT_RANGE": 0X2AEF,
    "ELECTRIC_CURRENT_SPECIFICATION": 0X2AF0,
    "ELECTRIC_CURRENT_STATISTICS": 0X2AF1,
    "ENERGY": 0X2AF2,
    "ENERGY_IN_A_PERIOD_OF_DAY": 0X2AF3,
    "EVENT_STATISTICS": 0X2AF4,
    "FIXED_STRING_16": 0X2AF5,
    "FIXED_STRING_24": 0X2AF6,
    "FIXED_STRING_36": 0X2AF7,
    "FIXED_STRING_8": 0X2AF8,
    "GENERIC_LEVEL": 0X2AF9,
    "GLOBAL_TRADE_ITEM_NUMBER": 0X2AFA,
    "ILLUMINANCE": 0X2AFB,
    "LUMINOUS_EFFICACY": 0X2AFC,
    "LUMINOUS_ENERGY": 0X2AFD,
    "LUMINOUS_EXPOSURE": 0X2AFE,
    "LUMINOUS_FLUX": 0X2AFF,
    "LUMINOUS_FLUX_RANGE": 0x2B00,
    "LUMINOUS_INTENSITY": 0x2B01,
    "MASS_FLOW": 0x2B02,
    "PERCEIVED_LIGHTNESS": 0x2B03,
    "PERCENTAGE_8": 0x2B04,
    "POWER": 0x2B05,
    "POWER_SPECIFICATION": 0x2B06,
    "RELATIVE_RUNTIME_IN_A_CURRENT_RANGE": 0x2B07,
    "RELATIVE_RUNTIME_IN_A_GENERIC_LEVEL_RANGE": 0x2B08,
    "RELATIVE_VALUE_IN_A_VOLTAGE_RANGE": 0x2B09,
    "RELATIVE_VALUE_IN_AN_ILLUMINANCE_RANGE": 0x2B0A,
    "RELATIVE_VALUE_IN_A_PERIOD_OF_DAY": 0x2B0B,
    "RELATIVE_VALUE_IN_A_TEMPERATURE_RANGE": 0x2B0C,
    "TEMPERATURE_8": 0x2B0D,
    "TEMPERATURE_8_IN_A_PERIOD_OF_DAY": 0x2B0E,
    "TEMPERATURE_8_STATISTICS": 0x2B0F,
    "TEMPERATURE_RANGE": 0x2B10,
    "TEMPERATURE_STATISTICS": 0x2B11,
    "TIME_DECIHOUR_8": 0x2B12,
    "TIME_EXPONENTIAL_8": 0x2B13,
    "TIME_HOUR_24": 0x2B14,
    "TIME_MILLISECOND_24": 0x2B15,
    "TIME_SECOND_16": 0x2B16,
    "TIME_SECOND_8": 0x2B17,
    "VOLTAGE": 0x2B18,
    "VOLTAGE_SPECIFICATION": 0x2B19,
    "VOLTAGE_STATISTICS": 0x2B1A,
    "VOLUME_FLOW": 0x2B1B,
    "CHROMATICITY_COORDINATE": 0x2B1C,
    "RC_FEATURE": 0x2B1D,
    "RC_SETTINGS": 0x2B1E,
    "RECONNECTION_CONFIGURATION_CONTROL_POINT": 0x2B1F,
    "IDD_STATUS_CHANGED": 0x2B20,
    "IDD_STATUS": 0x2B21,
    "IDD_ANNUNCIATION_STATUS": 0x2B22,
    "IDD_FEATURES": 0x2B23,
    "IDD_STATUS_READER_CONTROL_POINT": 0x2B24,
    "IDD_COMMAND_CONTROL_POINT": 0x2B25,
    "IDD_COMMAND_DATA": 0x2B26,
    "IDD_RECORD_ACCESS_CONTROL_POINT": 0x2B27,
    "IDD_HISTORY_DATA": 0x2B28,
    "CLIENT_SUPPORTED_FEATURES": 0x2B29,
    "DATABASE_HASH": 0x2B2A,
    "BSS_CONTROL_POINT": 0x2B2B,
    "BSS_RESPONSE": 0x2B2C,
    "EMERGENCY_ID": 0x2B2D,
    "EMERGENCY_TEXT": 0x2B2E,
    "ENHANCED_BLOOD_PRESSURE_MEASUREMENT": 0x2B34,
    "ENHANCED_INTERMEDIATE_CUFF_PRESSURE": 0x2B35,
    "BLOOD_PRESSURE_RECORD": 0x2B36,
    "BR_EDR_HANDOVER_DATA": 0x2B38,
    "BLUETOOTH_SIG_DATA": 0x2B39,
    "SERVER_SUPPORTED_FEATURES": 0x2B3A,
    "PHYSICAL_ACTIVITY_MONITOR_FEATURES": 0x2B3B,
    "GENERAL_ACTIVITY_INSTANTANEOUS_DATA": 0x2B3C,
    "GENERAL_ACTIVITY_SUMMARY_DATA": 0x2B3D,
    "CARDIORESPIRATORY_ACTIVITY_INSTANTANEOUS_DATA": 0x2B3E,
    "CARDIORESPIRATORY_ACTIVITY_SUMMARY_DATA": 0x2B3F,
    "STEP_COUNTER_ACTIVITY_SUMMARY_DATA": 0x2B40,
    "SLEEP_ACTIVITY_INSTANTANEOUS_DATA": 0x2B41,
    "SLEEP_ACTIVITY_SUMMARY_DATA": 0x2B42,
    "PHYSICAL_ACTIVITY_MONITOR_CONTROL_POINT": 0x2B43,
    "CURRENT_SESSION": 0x2B44,
    "SESSION": 0x2B45,
    "PREFERRED_UNITS": 0x2B46,
    "HIGH_RESOLUTION_HEIGHT": 0x2B47,
    "MIDDLE_NAME": 0x2B48,
    "STRIDE_LENGTH": 0x2B49,
    "HANDEDNESS": 0x2B4A,
    "DEVICE_WEARING_POSITION": 0x2B4B,
    "FOUR_ZONE_HEART_RATE_LIMITS": 0x2B4C,
    "HIGH_INTENSITY_EXERCISE_THRESHOLD": 0x2B4D,
    "ACTIVITY_GOAL": 0x2B4E,
    "SEDENTARY_INTERVAL_NOTIFICATION": 0x2B4F,
    "CALORIC_INTAKE": 0x2B50,
    "AUDIO_INPUT_STATE": 0x2B77,
    "GAIN_SETTINGS_ATTRIBUTE": 0x2B78,
    "AUDIO_INPUT_TYPE": 0x2B79,
    "AUDIO_INPUT_STATUS": 0x2B7A,
    "AUDIO_INPUT_CONTROL_POINT": 0x2B7B,
    "AUDIO_INPUT_DESCRIPTION": 0x2B7C,
    "VOLUME_STATE": 0x2B7D,
    "VOLUME_CONTROL_POINT": 0x2B7E,
    "VOLUME_FLAGS": 0x2B7F,
    "OFFSET_STATE": 0x2B80,
    "AUDIO_LOCATION": 0x2B81,
    "VOLUME_OFFSET_CONTROL_POINT": 0x2B82,
    "AUDIO_OUTPUT_DESCRIPTION": 0x2B83,
    "SET_IDENTITY_RESOLVING_KEY_CHARACTERISTIC": 0x2B84,
    "SIZE_CHARACTERISTIC": 0x2B85,
    "LOCK_CHARACTERISTIC": 0x2B86,
    "RANK_CHARACTERISTIC": 0x2B87,
    "DEVICE_TIME_FEATURE": 0x2B8E,
    "DEVICE_TIME_PARAMETERS": 0x2B8F,
    "DEVICE_TIME": 0x2B90,
    "DEVICE_TIME_CONTROL_POINT": 0x2B91,
    "TIME_CHANGE_LOG_DATA": 0x2B92,
    "MEDIA_PLAYER_NAME": 0x2B93,
    "MEDIA_PLAYER_ICON_OBJECT_ID": 0x2B94,
    "MEDIA_PLAYER_ICON_URL": 0x2B95,
    "TRACK_CHANGED": 0x2B96,
    "TRACK_TITLE": 0x2B97,
    "TRACK_DURATION": 0x2B98,
    "TRACK_POSITION": 0x2B99,
    "PLAYBACK_SPEED": 0x2B9A,
    "SEEKING_SPEED": 0x2B9B,
    "CURRENT_TRACK_SEGMENTS_OBJECT_ID": 0x2B9C,
    "CURRENT_TRACK_OBJECT_ID": 0x2B9D,
    "NEXT_TRACK_OBJECT_ID": 0x2B9E,
    "PARENT_GROUP_OBJECT_ID": 0x2B9F,
    "CURRENT_GROUP_OBJECT_ID": 0x2BA0,
    "PLAYING_ORDER": 0x2BA1,
    "PLAYING_ORDERS_SUPPORTED": 0x2BA2,
    "MEDIA_STATE": 0x2BA3,
    "MEDIA_CONTROL_POINT": 0x2BA4,
    "MEDIA_CONTROL_POINT_OPCODES_SUPPORTED": 0x2BA5,
    "SEARCH_RESULTS_OBJECT_ID": 0x2BA6,
    "SEARCH_CONTROL_POINT": 0x2BA7,
    "MEDIA_PLAYER_ICON_OBJECT_TYPE": 0x2BA9,
    "TRACK_SEGMENTS_OBJECT_TYPE": 0x2BAA,
    "TRACK_OBJECT_TYPE": 0x2BAB,
    "GROUP_OBJECT_TYPE": 0x2BAC,
    "CONSTANT_TONE_EXTENSION_ENABLE": 0x2BAD,
    "ADVERTISING_CONSTANT_TONE_EXTENSION_MINIMUM_LENGTH": 0x2BAE,
    "ADVERTISING_CONSTANT_TONE_EXTENSION_MINIMUM_TRANSMIT_COUNT": 0x2BAF,
    "ADVERTISING_CONSTANT_TONE_EXTENSION_TRANSMIT_DURATION": 0x2BB0,
    "ADVERTISING_CONSTANT_TONE_EXTENSION_INTERVAL": 0x2BB1,
    "ADVERTISING_CONSTANT_TONE_EXTENSION_PHY": 0x2BB2,
    "BEARER_PROVIDER_NAME": 0x2BB3,
    "BEARER_UCI": 0x2BB4,
    "BEARER_TECHNOLOGY": 0x2BB5,
    "BEARER_URI_SCHEMES_SUPPORTED_LIST": 0x2BB6,
    "BEARER_SIGNAL_STRENGTH": 0x2BB7,
    "BEARER_SIGNAL_STRENGTH_REPORTING_INTERVAL": 0x2BB8,
    "BEARER_LIST_CURRENT_CALLS": 0x2BB9,
    "CONTENT_CONTROL_ID": 0x2BBA,
    "STATUS_FLAGS": 0x2BBB,
    "INCOMING_CALL_TARGET_BEARER_URI": 0x2BBC,
    "CALL_STATE": 0x2BBD,
    "CALL_CONTROL_POINT": 0x2BBE,
    "CALL_CONTROL_POINT_OPTIONAL_OPCODES": 0x2BBF,
    "TERMINATION_REASON": 0x2BC0,
    "INCOMING_CALL": 0x2BC1,
    "CALL_FRIENDLY_NAME": 0x2BC2,
    "MUTE": 0x2BC3,
    "SINK_ASE": 0x2BC4,
    "SOURCE_ASE": 0x2BC5,
    "ASE_CONTROL_POINT": 0x2BC6,
    "BROADCAST_AUDIO_SCAN_CONTROL_POINT": 0x2BC7,
    "BROADCAST_RECEIVE_STATE": 0x2BC8,
    "SINK_PAC": 0x2BC9,
    "SINK_AUDIO_LOCATIONS": 0x2BCA,
    "SOURCE_PAC": 0x2BCB,
    "SOURCE_AUDIO_LOCATIONS": 0x2BCC,
    "AVAILABLE_AUDIO_CONTEXTS": 0x2BCD,
    "SUPPORTED_AUDIO_CONTEXTS": 0x2BCE,
    "AMMONIA_CONCENTRATION": 0x2BCF,
    "CARBON_MONOXIDE_CONCENTRATION": 0x2BD0,
    "METHANE_CONCENTRATION": 0x2BD1,
    "NITROGEN_DIOXIDE_CONCENTRATION": 0x2BD2,
    "NONMETHANE_VOLATILE_ORGANIC_COMPOUNDS_CONCENTRATION": 0x2BD3,
    "OZONE_CONCENTRATION": 0x2BD4,
    "PARTICULATE_MATTER_PM1_CONCENTRATION": 0x2BD5,
    "PARTICULATE_MATTER_PM2_5_CONCENTRATION": 0x2BD6,
    "PARTICULATE_MATTER_PM10_CONCENTRATION": 0x2BD7,
    "SULFUR_DIOXIDE_CONCENTRATION": 0x2BD8,
    "SULFUR_HEXAFLUORIDE_CONCENTRATION": 0x2BD9
};

const CHARACTERISTIC_OR_OBJECT_TYPE = {
    0x2A00: "Device Name",
    0x2A01: "Appearance",
    0x2A02: "Peripheral Privacy Flag",
    0x2A03: "Reconnection Address",
    0x2A04: "Peripheral Preferred Connection Parameters",
    0x2A05: "Service Changed",
    0x2A06: "Alert Level",
    0x2A07: "Tx Power Level",
    0x2A08: "Date Time",
    0x2A09: "Day of Week",
    0x2A0A: "Day Date Time",
    0x2A0C: "Exact Time 256",
    0x2A0D: "DST Offset",
    0x2A0E: "Time Zone",
    0x2A0F: "Local Time Information",
    0x2A11: "Time with DST",
    0x2A12: "Time Accuracy",
    0x2A13: "Time Source",
    0x2A14: "Reference Time Information",
    0x2A16: "Time Update Control Point",
    0x2A17: "Time Update State",
    0x2A18: "Glucose Measurement",
    0x2A19: "Battery Level",
    0x2A1B: "Battery Level State",
    0x2A1C: "Temperature Measurement",
    0x2A1D: "Temperature Type",
    0x2A1E: "Intermediate Temperature",
    0x2A21: "Measurement Interval",
    0x2A22: "Boot Keyboard Input Report",
    0x2A23: "System ID",
    0x2A24: "Model Number String",
    0x2A25: "Serial Number String",
    0x2A26: "Firmware Revision String",
    0x2A27: "Hardware Revision String",
    0x2A28: "Software Revision String",
    0x2A29: "Manufacturer Name String",
    0x2A2A: "IEEE 11073-20601 Regulatory Certification Data List",
    0x2A2B: "Current Time",
    0x2A31: "Scan Refresh",
    0x2A32: "Boot Keyboard Output Report",
    0x2A33: "Boot Mouse Input Report",
    0x2A34: "Glucose Measurement Context",
    0x2A35: "Blood Pressure Measurement",
    0x2A36: "Intermediate Cuff Pressure",
    0x2A37: "Heart Rate Measurement",
    0x2A38: "Body Sensor Location",
    0x2A39: "Heart Rate Control Point",
    0x2A3F: "Alert Status",
    0x2A40: "Ringer Control Point",
    0x2A41: "Ringer Setting",
    0x2A42: "Alert Category ID Bit Mask",
    0x2A43: "Alert Category ID",
    0x2A44: "Alert Notification Control Point",
    0x2A45: "Unread Alert Status",
    0x2A46: "New Alert",
    0x2A47: "Supported New Alert Category",
    0x2A48: "Supported Unread Alert Category",
    0x2A49: "Blood Pressure Feature",
    0x2A4A: "HID Information",
    0x2A4B: "Report Map",
    0x2A4C: "HID Control Point",
    0x2A4D: "Report",
    0x2A4E: "Protocol Mode",
    0x2A4F: "Scan Interval Window",
    0x2A50: "PnP ID",
    0x2A51: "Glucose Feature",
    0x2A52: "Record Access Control Point",
    0x2A53: "RSC Measurement",
    0x2A54: "RSC Feature",
    0x2A55: "SC Control Point",
    0x2A5A: "Aggregate",
    0x2A5B: "CSC Measurement",
    0x2A5C: "CSC Feature",
    0x2A5D: "Sensor Location",
    0x2A5E: "PLX Spot-Check Measurement",
    0x2A5F: "PLX Continuous Measurement",
    0x2A60: "PLX Features",
    0x2A63: "Cycling Power Measurement",
    0x2A64: "Cycling Power Vector",
    0x2A65: "Cycling Power Feature",
    0x2A66: "Cycling Power Control Point",
    0x2A67: "Location and Speed",
    0x2A68: "Navigation",
    0x2A69: "Position Quality",
    0x2A6A: "LN Feature",
    0x2A6B: "LN Control Point",
    0x2A6C: "Elevation",
    0x2A6D: "Pressure",
    0x2A6E: "Temperature",
    0x2A6F: "Humidity",
    0x2A70: "True Wind Speed",
    0x2A71: "True Wind Direction",
    0x2A72: "Apparent Wind Speed",
    0x2A73: "Apparent Wind Direction",
    0x2A74: "Gust Factor",
    0x2A75: "Pollen Concentration",
    0x2A76: "UV Index",
    0x2A77: "Irradiance",
    0x2A78: "Rainfall",
    0x2A79: "Wind Chill",
    0x2A7A: "Heat Index",
    0x2A7B: "Dew Point",
    0x2A7D: "Descriptor Value Changed",
    0x2A7E: "Aerobic Heart Rate Lower Limit",
    0x2A7F: "Aerobic Threshold",
    0x2A80: "Age",
    0x2A81: "Anaerobic Heart Rate Lower Limit",
    0x2A82: "Anaerobic Heart Rate Upper Limit",
    0x2A83: "Anaerobic Threshold",
    0x2A84: "Aerobic Heart Rate Upper Limit",
    0x2A85: "Date of Birth",
    0x2A86: "Date of Threshold Assessment",
    0x2A87: "Email Address",
    0x2A88: "Fat Burn Heart Rate Lower Limit",
    0x2A89: "Fat Burn Heart Rate Upper Limit",
    0x2A8A: "First Name",
    0x2A8B: "Five Zone Heart Rate Limits",
    0x2A8C: "Gender",
    0x2A8D: "Heart Rate Max",
    0x2A8E: "Height",
    0x2A8F: "Hip Circumference",
    0x2A90: "Last Name",
    0x2A91: "Maximum Recommended Heart Rate",
    0x2A92: "Resting Heart Rate",
    0x2A93: "Sport Type for Aerobic and Anaerobic Thresholds",
    0x2A94: "Three Zone Heart Rate Limits",
    0x2A95: "Two Zone Heart Rate Limits",
    0x2A96: "VO2 Max",
    0x2A97: "Waist Circumference",
    0x2A98: "Weight",
    0x2A99: "Database Change Increment",
    0x2A9A: "User Index",
    0x2A9B: "Body Composition Feature",
    0x2A9C: "Body Composition Measurement",
    0x2A9D: "Weight Measurement",
    0x2A9E: "Weight Scale Feature",
    0x2A9F: "User Control Point",
    0x2AA0: "Magnetic Flux Density - 2D",
    0x2AA1: "Magnetic Flux Density - 3D",
    0x2AA2: "Language",
    0x2AA3: "Barometric Pressure Trend",
    0x2AA4: "Bond Management Control Point",
    0x2AA5: "Bond Management Feature",
    0x2AA6: "Central Address Resolution",
    0x2AA7: "CGM Measurement",
    0x2AA8: "CGM Feature",
    0x2AA9: "CGM Status",
    0x2AAA: "CGM Session Start Time",
    0x2AAB: "CGM Session Run Time",
    0x2AAC: "CGM Specific Ops Control Point",
    0x2AAD: "Indoor Positioning Configuration",
    0x2AAE: "Latitude",
    0x2AAF: "Longitude",
    0x2AB0: "Local North Coordinate",
    0x2AB1: "Local East Coordinate",
    0x2AB2: "Floor Number",
    0x2AB3: "Altitude",
    0x2AB4: "Uncertainty",
    0x2AB5: "Location Name",
    0x2AB6: "URI",
    0x2AB7: "HTTP Headers",
    0x2AB8: "HTTP Status Code",
    0x2AB9: "HTTP Entity Body",
    0x2ABA: "HTTP Control Point",
    0x2ABB: "HTTPS Security",
    0x2ABC: "TDS Control Point",
    0x2ABD: "OTS Feature",
    0x2ABE: "object name",
    0x2ABF: "object type",
    0x2AC0: "object size",
    0x2AC1: "object first created",
    0x2AC2: "object last modified",
    0x2AC3: "object ID",
    0x2AC4: "object properties",
    0x2AC5: "object actioncontrol point",
    0x2AC6: "object list control point",
    0x2AC7: "object list filter",
    0x2AC8: "object changed",
    0x2AC9: "Resolvable Private Address Only",
    0x2ACA: "Unspecified",
    0x2ACB: "Directory Listing",
    0x2ACC: "Fitness Machine Feature",
    0x2ACD: "Treadmill Data",
    0x2ACE: "Cross Trainer Data",
    0x2ACF: "Step Climber Data",
    0x2AD0: "Stair Climber Data",
    0x2AD1: "Rower Data",
    0x2AD2: "Indoor Bike Data",
    0x2AD3: "Training Status",
    0x2AD4: "Supported Speed Range",
    0x2AD5: "Supported Inclination Range",
    0x2AD6: "Supported Resistance Level Range",
    0x2AD7: "Supported Heart Rate Range",
    0x2AD8: "Supported Power Range",
    0x2AD9: "Fitness Machine Control Point",
    0x2ADA: "Fitness Machine Status",
    0x2ADB: "Mesh Provisioning Data In",
    0X2ADC: "Mesh Provisioning Data Out",
    0X2ADD: "Mesh Proxy Data In",
    0X2ADE: "Mesh Proxy Data Out",
    0X2AE0: "Average Current",
    0X2AE1: "Average Voltage",
    0X2AE2: "Boolean",
    0X2AE3: "Chromatic Distance From Planckian",
    0X2AE4: "Chromaticity Coordinates",
    0X2AE5: "Chromaticity in CCT And Duv Values",
    0X2AE6: "Chromaticity Tolerance",
    0X2AE7: "CIE 13.3-1995 Color Rendering Index",
    0X2AE8: "Coefficient",
    0X2AE9: "Correlated Color Temperature",
    0X2AEA: "Count 16",
    0X2AEB: "Count 24",
    0X2AEC: "Country Code",
    0X2AED: "Date UTC",
    0X2AEE: "Electric Current",
    0X2AEF: "Electric Current Range",
    0X2AF0: "Electric Current Specification",
    0X2AF1: "Electric Current Statistics",
    0X2AF2: "Energy",
    0X2AF3: "Energy In A Period Of Day",
    0X2AF4: "Event Statistics",
    0X2AF5: "Fixed String 16",
    0X2AF6: "Fixed String 24",
    0X2AF7: "Fixed String 36",
    0X2AF8: "Fixed String 8",
    0X2AF9: "Generic Level",
    0X2AFA: "Global Trade Item Number",
    0X2AFB: "Illuminance",
    0X2AFC: "Luminous Efficacy",
    0X2AFD: "Luminous Energy",
    0X2AFE: "Luminous Exposure",
    0X2AFF: "Luminous Flux",
    0x2B00: "Luminous Flux Range",
    0x2B01: "Luminous Intensity",
    0x2B02: "Mass Flow",
    0x2B03: "Perceived Lightness",
    0x2B04: "Percentage 8",
    0x2B05: "Power",
    0x2B06: "Power Specification",
    0x2B07: "Relative Runtime In A Current Range",
    0x2B08: "Relative Runtime In A Generic Level Range",
    0x2B09: "Relative Value In A Voltage Range",
    0x2B0A: "Relative Value In An Illuminance Range",
    0x2B0B: "Relative Value In A Period Of Day",
    0x2B0C: "Relative Value In A Temperature Range",
    0x2B0D: "Temperature 8",
    0x2B0E: "Temperature 8 In A Period Of Day",
    0x2B0F: "Temperature 8 Statistics",
    0x2B10: "Temperature Range",
    0x2B11: "Temperature Statistics",
    0x2B12: "Time Decihour 8",
    0x2B13: "Time Exponential 8",
    0x2B14: "Time Hour 24",
    0x2B15: "Time Millisecond 24",
    0x2B16: "Time Second 16",
    0x2B17: "Time Second 8",
    0x2B18: "Voltage",
    0x2B19: "Voltage Specification",
    0x2B1A: "Voltage Statistics",
    0x2B1B: "Volume Flow",
    0x2B1C: "Chromaticity Coordinate",
    0x2B1D: "RC Feature",
    0x2B1E: "RC Settings",
    0x2B1F: "Reconnection Configuration Control Point",
    0x2B20: "IDD Status Changed",
    0x2B21: "IDD Status",
    0x2B22: "IDD Annunciation Status",
    0x2B23: "IDD Features",
    0x2B24: "IDD Status Reader Control Point",
    0x2B25: "IDD Command Control Point",
    0x2B26: "IDD Command Data",
    0x2B27: "IDD Record Access Control Point",
    0x2B28: "IDD History Data",
    0x2B29: "Client Supported Features",
    0x2B2A: "Database Hash",
    0x2B2B: "BSS Control Point",
    0x2B2C: "BSS Response",
    0x2B2D: "Emergency ID",
    0x2B2E: "Emergency Text",
    0x2B34: "Enhanced Blood Pressure Measurement",
    0x2B35: "Enhanced Intermediate Cuff Pressure",
    0x2B36: "Blood Pressure Record",
    0x2B38: "BR-EDR Handover Data",
    0x2B39: "Bluetooth SIG Data",
    0x2B3A: "Server Supported Features",
    0x2B3B: "Physical Activity Monitor Features",
    0x2B3C: "General Activity Instantaneous Data",
    0x2B3D: "General Activity Summary Data",
    0x2B3E: "CardioRespiratory Activity Instantaneous Data",
    0x2B3F: "CardioRespiratory Activity Summary Data",
    0x2B40: "Step Counter Activity Summary Data",
    0x2B41: "Sleep Activity Instantaneous Data",
    0x2B42: "Sleep Activity Summary Data",
    0x2B43: "Physical Activity Monitor Control Point",
    0x2B44: "Current Session",
    0x2B45: "Session",
    0x2B46: "Preferred Units",
    0x2B47: "High Resolution Height",
    0x2B48: "Middle Name",
    0x2B49: "Stride Length",
    0x2B4A: "Handedness",
    0x2B4B: "Device Wearing Position",
    0x2B4C: "Four Zone Heart Rate Limits",
    0x2B4D: "High Intensity Exercise Threshold",
    0x2B4E: "Activity Goal",
    0x2B4F: "Sedentary Interval Notification",
    0x2B50: "Caloric Intake",
    0x2B77: "Audio Input State",
    0x2B78: "Gain Settings Attribute",
    0x2B79: "Audio Input Type",
    0x2B7A: "Audio Input Status",
    0x2B7B: "Audio Input Control Point",
    0x2B7C: "Audio Input Description",
    0x2B7D: "Volume State",
    0x2B7E: "Volume Control Point",
    0x2B7F: "Volume Flags",
    0x2B80: "Offset State",
    0x2B81: "Audio Location",
    0x2B82: "Volume Offset Control Point",
    0x2B83: "Audio Output Description",
    0x2B84: "Set Identity Resolving Key Characteristic",
    0x2B85: "Size Characteristic",
    0x2B86: "Lock Characteristic",
    0x2B87: "Rank Characteristic",
    0x2B8E: "Device Time Feature",
    0x2B8F: "Device Time Parameters",
    0x2B90: "Device Time",
    0x2B91: "Device Time Control Point",
    0x2B92: "Time Change Log Data",
    0x2B93: "Media Player Name",
    0x2B94: "Media Player Icon Object ID",
    0x2B95: "Media Player Icon URL",
    0x2B96: "Track Changed",
    0x2B97: "Track Title",
    0x2B98: "Track Duration",
    0x2B99: "Track Position",
    0x2B9A: "Playback Speed",
    0x2B9B: "Seeking Speed",
    0x2B9C: "Current Track Segments Object ID",
    0x2B9D: "Current Track Object ID",
    0x2B9E: "Next Track Object ID",
    0x2B9F: "Parent Group Object ID",
    0x2BA0: "Current Group Object ID",
    0x2BA1: "Playing Order",
    0x2BA2: "Playing Orders Supported",
    0x2BA3: "Media State",
    0x2BA4: "Media Control Point",
    0x2BA5: "Media Control Point Opcodes Supported",
    0x2BA6: "Search Results Object ID",
    0x2BA7: "Search Control Point",
    0x2BA9: "Media Player Icon Object Type",
    0x2BAA: "Track Segments Object Type",
    0x2BAB: "Track Object Type",
    0x2BAC: "Group Object Type",
    0x2BAD: "Constant Tone Extension Enable",
    0x2BAE: "Advertising Constant Tone Extension Minimum Length",
    0x2BAF: "Advertising Constant Tone Extension Minimum Transmit Count",
    0x2BB0: "Advertising Constant Tone Extension Transmit Duration",
    0x2BB1: "Advertising Constant Tone Extension Interval",
    0x2BB2: "Advertising Constant Tone Extension PHY",
    0x2BB3: "Bearer Provider Name",
    0x2BB4: "Bearer UCI",
    0x2BB5: "Bearer Technology",
    0x2BB6: "Bearer URI Schemes Supported List",
    0x2BB7: "Bearer Signal Strength",
    0x2BB8: "Bearer Signal Strength Reporting Interval",
    0x2BB9: "Bearer List Current Calls",
    0x2BBA: "Content Control ID",
    0x2BBB: "Status Flags",
    0x2BBC: "Incoming Call Target Bearer URI",
    0x2BBD: "Call State",
    0x2BBE: "Call Control Point",
    0x2BBF: "Call Control Point Optional Opcodes",
    0x2BC0: "Termination Reason",
    0x2BC1: "Incoming Call",
    0x2BC2: "Call Friendly Name",
    0x2BC3: "Mute",
    0x2BC4: "Sink ASE",
    0x2BC5: "Source ASE",
    0x2BC6: "ASE Control Point",
    0x2BC7: "Broadcast Audio Scan Control Point",
    0x2BC8: "Broadcast Receive State",
    0x2BC9: "Sink PAC",
    0x2BCA: "Sink Audio Locations",
    0x2BCB: "Source PAC",
    0x2BCC: "Source Audio Locations",
    0x2BCD: "Available Audio Contexts",
    0x2BCE: "Supported Audio Contexts",
    0x2BCF: "Ammonia Concentration",
    0x2BD0: "Carbon Monoxide Concentration",
    0x2BD1: "Methane Concentration",
    0x2BD2: "Nitrogen Dioxide Concentration",
    0x2BD3: "Non-Methane Volatile Organic Compounds Concentration",
    0x2BD4: "Ozone Concentration",
    0x2BD5: "Particulate Matter - PM1 Concentration",
    0x2BD6: "Particulate Matter - PM2.5 Concentration",
    0x2BD7: "Particulate Matter - PM10 Concentration",
    0x2BD8: "Sulfur Dioxide Concentration",
    0x2BD9: "Sulfur Hexafluoride Concentration"
};

export {
    CHARACTERISTIC_OR_OBJECT_TYPE,
    CHARACTERISTIC_UUID
};
